import CryptoKit
import Foundation

/// Safe to retain because it describes only the credential-free environment
/// generated by the kernel. Provider secrets require a separate, opaque,
/// non-serializable capability and must never be added to this receipt.
struct KernelProcessEnvironmentReceipt: Codable, Hashable, Sendable {
    var policy: KernelEnvironmentPolicy
    var variableNames: [String]
    var environmentDigest: ContentDigest
}

struct AuthorizedKernelProcessEnvironment: Sendable {
    var environment: [String: String]
    var receipt: KernelProcessEnvironmentReceipt
}

enum KernelProcessEnvironmentAuthorizationError: Error, Equatable {
    case callerSuppliedEnvironmentForbidden
    case declaredAllowlistNotMaterialized
}

/// Constructs launch environment authority from the ratified execution
/// profile. The caller supplies no environment bytes: this prevents ambient
/// host credentials from becoming worker authority by dictionary injection.
struct KernelProcessEnvironmentAuthorizer: Sendable {
    static let minimalEnvironment: [String: String] = [
        "LANG": "C",
        "LC_ALL": "C",
        "NO_COLOR": "1",
        "PATH": "/usr/bin:/bin:/usr/sbin:/sbin"
    ]

    func authorize(
        callerSuppliedEnvironment: [String: String],
        policy: KernelEnvironmentPolicy
    ) throws -> AuthorizedKernelProcessEnvironment {
        guard callerSuppliedEnvironment.isEmpty else {
            throw KernelProcessEnvironmentAuthorizationError
                .callerSuppliedEnvironmentForbidden
        }
        guard policy == .minimalKernelAllowlist else {
            // The contract can reserve this policy only when a user capability
            // exists, but no typed per-name/value issuer exists yet. Do not
            // infer declarations or inherit host values in the meantime.
            throw KernelProcessEnvironmentAuthorizationError
                .declaredAllowlistNotMaterialized
        }
        let environment = Self.minimalEnvironment
        return AuthorizedKernelProcessEnvironment(
            environment: environment,
            receipt: KernelProcessEnvironmentReceipt(
                policy: policy,
                variableNames: environment.keys.sorted(),
                environmentDigest: Self.environmentDigest(environment)
            )
        )
    }

    /// Length-prefixes every sorted UTF-8 key and value so the digest has one
    /// unambiguous representation even when values contain separators.
    static func environmentDigest(
        _ environment: [String: String]
    ) -> ContentDigest {
        var hasher = SHA256()
        for key in environment.keys.sorted() {
            update(&hasher, with: Data(key.utf8))
            update(&hasher, with: Data((environment[key] ?? "").utf8))
        }
        return ContentDigest(
            hasher.finalize().map { String(format: "%02x", $0) }.joined()
        )
    }

    private static func update(
        _ hasher: inout SHA256,
        with bytes: Data
    ) {
        var count = UInt64(bytes.count).bigEndian
        withUnsafeBytes(of: &count) { hasher.update(bufferPointer: $0) }
        hasher.update(data: bytes)
    }
}
